# The URL the site will be built for
base_url = "https://thedevleon.github.io"
title = "devleon"
description = "portfolio and blog of devleon"
default_language = "en"
generate_sitemap = true
generate_robots_txt = true

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "apollo"
taxonomies = [{ name = "tags" }]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
# footnotes at the bottom
bottom_footnotes = true

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[extra]
theme = "auto"
socials = [
  { name = "linkedin", url = "https://www.linkedin.com/in/devleon/", icon = "linkedin" },
  { name = "github", url = "https://github.com/thedevleon", icon = "github" },
]
menu = [
    { name = "/home", url = "/", weight = 1 },
    { name = "/posts", url = "/posts", weight = 2 },
    { name = "/projects", url = "/projects", weight = 3 },
    { name = "/tags", url = "/tags", weight = 4 },
]
toc = true
use_cdn = true
# logo = "rust.svg"
favicon = "rust.png"
fancy_code = true
dynamic_note = true
mathjax = true
mathjax_dollar_inline_enable = true
comment = true
stylesheets = [
  "custom.css",           # static/custom.css
]

[extra.analytics]
enabled = true

[extra.analytics.goatcounter]
user = "devleon"           # Your GoatCounter username